/**:
    ros__parameters:
        connection_type: tcp
        device: 172.31.0.90:3001
        publish_novatel_positions: True
        publish_novatel_velocity: True
        publish_novatel_dual_antenna_heading: True
        publish_dual_antenna_diagnostic: True
        publish_novatel_heading2: True
        publish_novatel_utm_positions: True
        publish_novatel_xyz_positions: True
        publish_range_messages: True
        publish_sync_diagnostic: True
        publish_time_messages: True
        publish_time_reference: True
        publish_trackstat: True
        verbose: True
        imu_sample_rate: -1.0
        use_binary_messages: False
        publish_imu_messages: False
        publish_novatel_psrdop2: True
        wait_for_sync: True
        frame_id: gps_antenna_right_sensor
        imu_frame_id: imu
